package com.swp391_8.schoolhealth.dto;

import lombok.Data;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class StudentHealthCheckupDTO { // Renamed DTO
    private Integer checkupResultId;
    private Integer eventId;
    private String eventName; // For display
    private String studentCode;
    private String studentName; // For display
    private LocalDate checkupDate;

    // Vision
    private String visionLeft;
    private String visionRight;
    private String visionNotes;

    // Hearing
    private String hearingLeft;
    private String hearingRight;
    private String hearingNotes;

    // Dental
    private String dentalOralHealthStatus;
    private String dentalNotes;

    // Scoliosis
    private String scoliosisScreeningResult;
    private String scoliosisNotes;

    // Vitals
    private Integer bloodPressureSystolic;
    private Integer bloodPressureDiastolic;
    private Integer heartRate;
    private Double temperatureCelsius;
    private Double heightCm;
    private Double weightKg;
    private Double bmi;
    private String bmiCategory;

    // General
    private String generalObservations;
    private String recommendations;

    // Consent
    private String parentConsentStatus; // String representation of Enum
    private String consentByParentUsername; // Changed from consentByParentCode to consentByParentUsername
    private String consentByParentName; // For display
    private LocalDate consentDate;

    // Communication & Follow-up
    private String parentCommunicationNotes;
    private Boolean followUpNeeded;
    private LocalDate followUpDate;
    private String followUpNotes;

    // Audit
    private Integer conductedByUserId;
    private String conductedByUserName; // For display
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // Add setter for conductedByUserName if not generated by Lombok
    public void setConductedByUserName(String conductedByUserName) {
        this.conductedByUserName = conductedByUserName;
    }
}
